[build]
  command = "npm run build"
  publish = "dist"

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "SAMEORIGIN"
    Cross-Origin-Opener-Policy = "same-origin-allow-popups"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200